[phases.setup]
nixPkgs = ["python311", "chromium", "chromedriver"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python bot.py"

[env]
CHROME_BIN = "/run/current-system/sw/bin/chromium"
CHROMEDRIVER_PATH = "/run/current-system/sw/bin/chromedriver"
